language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - nightly
allow_failures:
  - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("GeneralizedMetropolisHastings"); Pkg.test("GeneralizedMetropolisHastings"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("GeneralizedMetropolisHastings")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
